# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python
build:
  os: ubuntu-20.04 
  tools:
    python: "3.11"

python:
  install:
    - requirements: docs/sphinx.txt
    - method: pip
      path: .
      extra_requirements:
        - python-casacore

# Configuration for Sphinx documentation
sphinx:
   configuration: docs/source/conf.py
   fail_on_warning: False
